<a href="https://colab.research.google.com/github/theabhinav0231/dive_into_deep_learning_book/blob/main/d2l_preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors -> n-dimensional arrays, supports automatic differentiation, leverages GPUs to accelerate numerical computation, Numpy only uses CPUs.
In one-dimensional case, a tensor is called a vector.With two-dimensional, a tensor is called a matrix, with k>2, just refer to object as kth-order tensor.


In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x  # each value is called an element of the tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
# to get total number of elements in a tensor
x.numel() # len(x) will also work

12

In [4]:
# to get shape of the tensor i.e. the length along each axis
x.shape

torch.Size([12])

In [5]:
# to get the shape of a tensor without altering its size or values, by reshape.
# a vector x of shape (12,) to a matrix X with shape (3, 4). the elements of our vector are  thus x[3] == X[0, 3].
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3, 4)

tensor([[ 1.2464,  1.8489, -0.9687,  1.2618],
        [ 1.7570, -0.4815, -0.4049, -0.1145],
        [-0.8045,  2.3419,  1.6789, -1.3918]])

In [9]:
X = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
X[-1]

tensor([4, 3, 2, 1])

In [11]:
X[1:3]

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [12]:
X[1, 2] = 17
X

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4],
        [ 4,  3,  2,  1]])

In [13]:
X[:2, :]

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4]])

In [14]:
X[:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 4,  3,  2,  1]])

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
# Tensor concatenation
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [17]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [18]:
# binary tensor
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [19]:
# sun
X.sum()

tensor(66.)

In [20]:
# Broadcasting - element wise operation
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
c = torch.arange(4).reshape((2, 2))
c

tensor([[0, 1],
        [2, 3]])

In [22]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [24]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

Data Preprocessing -
Pandas!

In [25]:
# Creating a csv file, a dataset of homes
import os
os.makedirs(os.path.join("..", "data"), exist_ok=True)
data_file = os.path.join("..", "data", "house_tiny.csv")
with open(data_file, "w") as f:
  f.write("""NumRooms, RoofType, Price
  NA, NA, 127500
  2, NA, 106000
  4, Slate, 178100
  NA, NA, 140000""")

In [26]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

  NumRooms  RoofType   Price
0       NA        NA  127500
1        2        NA  106000
2        4     Slate  178100
3       NA        NA  140000


In [27]:
""" We can treat NaN
as a category. Since the RoofType column takes values Slate and NaN, pandas can convert
this column into two columns RoofType_Slate and RoofType_nan. A row whose roof type
is Slate will set values of RoofType_Slate and RoofType_nan to 1 and 0, respectively.
The converse holds for a row with a missing RoofType value"""

' We can treat NaN\nas a category. Since the RoofType column takes values Slate and NaN, pandas can convert\nthis column into two columns RoofType_Slate and RoofType_nan. A row whose roof type\nis Slate will set values of RoofType_Slate and RoofType_nan to 1 and 0, respectively.\nThe converse holds for a row with a missing RoofType value'

In [28]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms_  2  NumRooms_  4  NumRooms_  NA  NumRooms_nan   RoofType_ NA  \
0         False         False           True         False           True   
1          True         False          False         False           True   
2         False          True          False         False          False   
3         False         False           True         False           True   

    RoofType_ Slate   RoofType_nan  
0             False          False  
1             False          False  
2              True          False  
3             False          False  


In [29]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms_  2  NumRooms_  4  NumRooms_  NA  NumRooms_nan   RoofType_ NA  \
0         False         False           True         False           True   
1          True         False          False         False           True   
2         False          True          False         False          False   
3         False         False           True         False           True   

    RoofType_ Slate   RoofType_nan  
0             False          False  
1             False          False  
2              True          False  
3             False          False  


In [30]:
# Conversion to tensor format
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[0., 0., 1., 0., 1., 0., 0.],
         [1., 0., 0., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0., 1., 0.],
         [0., 0., 1., 0., 1., 0., 0.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

Scalers are 0th-order tensors, vectors are 1st-order tensors and matrcies are 2nd-order tensors.

Tensors give us a way of describing nth-order arrays.


In [31]:
# Tensoe Arithmetic
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [32]:
A*B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [36]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [37]:
# Sum the elements of tensor
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [39]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [40]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [41]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [45]:
A.numel() # gives the number of elements

6

In [46]:
len(A) # gives the length of the matrix

2

In [48]:
A.mean(), A.sum()/A.numel(), A.sum()/len(A)

(tensor(2.5000), tensor(2.5000), tensor(7.5000))

In [49]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [50]:
# 47