<a href="https://colab.research.google.com/github/theabhinav0231/dive_into_deep_learning_book/blob/main/d2l_preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors -> n-dimensional arrays, supports automatic differentiation, leverages GPUs to accelerate numerical computation, Numpy only uses CPUs.
In one-dimensional case, a tensor is called a vector.With two-dimensional, a tensor is called a matrix, with k>2, just refer to object as kth-order tensor.


In [25]:
import torch

In [26]:
x = torch.arange(12, dtype=torch.float32)
x  # each value is called an element of the tensor

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [27]:
# to get total number of elements in a tensor
x.numel() # len(x) will also work

12

In [28]:
# to get shape of the tensor i.e. the length along each axis
x.shape

torch.Size([12])

In [29]:
# to get the shape of a tensor without altering its size or values, by reshape.
# a vector x of shape (12,) to a matrix X with shape (3, 4). the elements of our vector are  thus x[3] == X[0, 3].
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [32]:
torch.randn(3, 4)

tensor([[-3.1638,  0.4106, -0.8627,  0.0823],
        [ 0.2045, -0.1184, -1.1509, -0.1852],
        [-0.5576,  0.2283, -0.8377,  0.1873]])

In [33]:
X = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [34]:
X[-1]

tensor([4, 3, 2, 1])

In [35]:
X[1:3]

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [36]:
X[1, 2] = 17
X

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4],
        [ 4,  3,  2,  1]])

In [37]:
X[:2, :]

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4]])

In [38]:
X[:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 4,  3,  2,  1]])

In [39]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [40]:
# Tensor concatenation
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [41]:
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [42]:
# binary tensor
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [43]:
# sun
X.sum()

tensor(66.)

In [44]:
# Broadcasting - element wise operation
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [45]:
c = torch.arange(4).reshape((2, 2))
c

tensor([[0, 1],
        [2, 3]])

In [46]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [48]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [49]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

Data Preprocessing -
Pandas!

In [50]:
# Creating a csv file, a dataset of homes
import os
os.makedirs(os.path.join("..", "data"), exist_ok=True)
data_file = os.path.join("..", "data", "house_tiny.csv")
with open(data_file, "w") as f:
  f.write("""NumRooms, RoofType, Price
  NA, NA, 127500
  2, NA, 106000
  4, Slate, 178100
  NA, NA, 140000""")

In [51]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

  NumRooms  RoofType   Price
0       NA        NA  127500
1        2        NA  106000
2        4     Slate  178100
3       NA        NA  140000


In [53]:
""" We can treat NaN
as a category. Since the RoofType column takes values Slate and NaN, pandas can convert
this column into two columns RoofType_Slate and RoofType_nan. A row whose roof type
is Slate will set values of RoofType_Slate and RoofType_nan to 1 and 0, respectively.
The converse holds for a row with a missing RoofType value"""

' We can treat NaN\nas a category. Since the RoofType column takes values Slate and NaN, pandas can convert\nthis column into two columns RoofType_Slate and RoofType_nan. A row whose roof type\nis Slate will set values of RoofType_Slate and RoofType_nan to 1 and 0, respectively.\nThe converse holds for a row with a missing RoofType value'

In [52]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms_  2  NumRooms_  4  NumRooms_  NA  NumRooms_nan   RoofType_ NA  \
0         False         False           True         False           True   
1          True         False          False         False           True   
2         False          True          False         False          False   
3         False         False           True         False           True   

    RoofType_ Slate   RoofType_nan  
0             False          False  
1             False          False  
2              True          False  
3             False          False  


In [54]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms_  2  NumRooms_  4  NumRooms_  NA  NumRooms_nan   RoofType_ NA  \
0         False         False           True         False           True   
1          True         False          False         False           True   
2         False          True          False         False          False   
3         False         False           True         False           True   

    RoofType_ Slate   RoofType_nan  
0             False          False  
1             False          False  
2              True          False  
3             False          False  


In [55]:
# Conversion to tensor format
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[0., 0., 1., 0., 1., 0., 0.],
         [1., 0., 0., 0., 1., 0., 0.],
         [0., 1., 0., 0., 0., 1., 0.],
         [0., 0., 1., 0., 1., 0., 0.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))